services:
  db:
    image: postgres:15-alpine
    # restart: always
    networks:
      - app-network
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432" # So you can connect with GUI like TablePlus
    volumes:
      - postgres_data:/var/lib/postgresql/data # Keep db data persistent over container shutdown & restart

  frontend:
    build:
      context: ./simple_frontend
      dockerfile: Dockerfile
    container_name: simple_frontend_container
    # restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./self-signed-ssl/cert.pem:/etc/nginx/certs/default.crt:ro
      - ./self-signed-ssl/key.pem:/etc/nginx/certs/default.key:ro

  backend:
    build:
      context: ./simple_backend
      dockerfile: Dockerfile
    container_name: simple_backend_container
    # restart: always
    volumes:
      - ./simple_backend:/app # Bind Mounts
      - /app/node_modules # Anonymous volume keeps these folders seperate from coding environment
    # We don't need to map ports to the host if only Nginx needs to talk to it
    expose:
      - "5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgres://dev_user:dev_password@db:5432/dev_db
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
